ory/elements

- src/react-components/ory/user-auth-card.tsx
- src/react-components/ory/user-consent-card.tsx
- src/react-components/ory/user-error-card.tsx
- src/react-components/ory/user-settings-card.tsx
- src/theme/checkbox.css.ts
I was playing around with elements, and saw the UserAuthCard have the className which wasn't being respected. I determined that this should be passed down to the Card component. I have also fixed this on the other card components.
It is useful for playing around with un-themeable things such as card width. (There is for instance a max-width set on the component, which I would like to unset).
I also included a small fix for using `justify-content: start`, which blows up my build log with this error: `[vite:css] start value has mixed support, consider using flex-start instead`. It then proceeds to print the line where the error is, but since the css is minified, it prints the whole style.css to my log.
An issue would be too much overhead for this small fix.
If this pull request addresses a …
> fix: respect classname in card components

- Makefile
- README.md
- contrib/sdk/.gitignore
- contrib/sdk/typescript.yml
- examples/preact-spa/src/app.tsx
- examples/preact-spa/src/login.tsx
- examples/preact-spa/src/recovery.tsx
- examples/preact-spa/src/register.tsx
- examples/preact-spa/src/sdk.ts
- examples/preact-spa/src/settings.tsx
- examples/preact-spa/src/verification.tsx
- examples/react-spa/src/Dashboard.tsx
- examples/react-spa/src/Login.tsx
- examples/react-spa/src/Recovery.tsx
- examples/react-spa/src/Registration.tsx
- examples/react-spa/src/Settings.tsx
- examples/react-spa/src/Verification.tsx
- examples/react-spa/src/sdk.ts
- openapitools.json
- package-lock.json
- package.json
- src/react-components/ory/helpers/types.ts
- src/react-components/ory/helpers/user-auth-form.tsx
- src/react-components/ory/user-auth-card.tsx
- src/react-components/ory/user-error-card.tsx
- src/react-components/ory/user-settings-card.tsx
> chore: update SDK to V1

- src/react-components/message.tsx
- src/react-components/ory/helpers/error-messages.tsx
- src/theme/message.css.ts
Add missing `success` state to be handled via UI. 
https://github.com/ory-corp/cloud/issues/3221
> fix: handle success state of message

- examples/nextjs-spa/styles/globals.css
> fix: nav overlaps container on mobile

- src/react-components/button-link.tsx
- src/react-components/ory/helpers/common.tsx
- src/react-components/ory/sections/login-section.tsx
- src/react-components/ory/user-auth-card.spec.tsx
- src/react-components/ory/user-auth-card.tsx
- src/react-components/ory/user-error-card.tsx
Fixes #58
This PR adds the option to specify a link handler in order to make use of client side navigation. This is fully backward compatible, without introducing any new parameters which have to be passed around.
This is achieved by extending the type of `href` in the `ButtonLink` component to also accept a tuple of a URL and a handler. When this tuple is defined, the default click event will be prevented and the handler will be called with the URL.
In it's simplest form, this allows to easily use React's navigation feature like this:
```typescript
const Login = () : JSX.Element => {
const navigate = useNavigate();
// …
return (
<UserAuthCard
flow={flow}
flowType="login"
additionalProps={{ logoutURL: ["/logout", navigate] }}
/>,
);
};
```
If this pull request addresses a security …
> feat: add href handler for ButtonLink component

- src/common/useIdWithFallback.ts
This PR fixes a compile error in projects using `React 17`. The change introduced in #113 implements unique IDs for components assuming that the `useId` react hook will be available. The proposed fix changes the import format to exclude the `useId` import from the build.
See conversation in #120 
Sample dependencies to reproduce the issue:
```json
"dependencies": {
"@ory/elements": "0.0.1-beta.7",
"loader-utils": "3.2.1",
"react": "17.0.2",
"react-dom": "17.0.2",
"react-scripts": "5.0.1"
},
"devDependencies": {
"@types/react": "17.0.2",
"@types/react-dom": "17.0.2",
"typescript": "5.0.2"
},
```
> fix: useIdWithFallback for react 17 and lower

- packages/markup/package.json
- packages/preact/package.json
- packages/react/package.json
- packages/test/package.json
Using `exports` in `package.json` means the `types` field is no longer used and types cannot be imported and results in the error below. I have added a `types` property to `exports` field to fix the issue
```
Could not find a declaration file for module '@ory/elements'. ‘XXXX/node_modules/@ory/elements/dist/index.mjs' implicitly has an 'any' type.
There are types at ‘XXXX/node_modules/@ory/elements/dist/index.d.ts', but this result could not be resolved when respecting package.json "exports". The '@ory/elements' library may need to update its package.json or typings.ts(7016)
```
See https://www.typescriptlang.org/docs/handbook/esm-node.html#packagejson-exports-imports-and-self-referencing for details.
The original `types` fields are left in place for use by older versions of Typescript. …
> fix: corrects "Could not find a declaration file for module '@ory/elements'" error

- src/assets/passwordInput.js
- src/react-components/input-field.tsx
- src/test/models/AuthPage.ts
- src/theme/input-field.css.ts
A form cannot have two input fields with the same name. Unfortunately we need to also support express server-side rendering which does not include much JS on the client. 
Due to the previous implementation only being in CSS and with limited browser support, this PR addresses those issues by implementing a strategy that works for both React and Express. 
In the end we have more JS, but it's minimal and vanilla. We now never have more than 1 input field on the dom related to password and will only display the custom field for password entry. The visibility toggle has also been updated to be a `div` element with the `dataset` property keeping the state for the visibility icon to swap via css.  
https://github.com/ory/elements/issues/116
If this pull request addresses a security …
> fix: password input field

- src/react-components/ory/user-settings-screen.tsx
- src/stories/Ory/SettingsScreen.stories.tsx
Because the iteration string was `lookupSecret`, but the group is `lookup_secret`, that section would never be displayed.
> fix: settings screen group filter for lookupSecret

- examples/react-spa/src/Login.tsx
- src/react-components/ory/user-auth-card.spec.tsx
- src/react-components/ory/user-auth-card.tsx
- src/stories/Ory/Auth.stories.tsx
This PR addresses two minor issues:
1. Previously, after creating a login flow, its ID was not included in the query parameters, unlike the other flows.
2. The signup URL was always rendered, even when it was `undefined`. This resulted in an unclickable link. Additionally, this change allows users who haven't enabled registration to hide the URL.
> fix: `additionalProps` should be conditional on the `UserAuthCard`

- src/react-components/ory/sections/auth-code-section.spec.tsx
- src/react-components/ory/sections/auth-code-section.tsx
- src/stories/Ory/Auth.stories.tsx
- src/stories/Ory/register-flow-code.json
Add registration with code registration story.
Cleanup the auto-code section component.
> feat: show registration with code in storybook & cleanup component

- src/react-components/input-field.tsx
- src/react-components/ory/helpers/node.spec.tsx
- src/react-components/ory/sections/auth-code-section.spec.tsx
- src/react-components/ory/sections/auth-code-section.tsx
Hide the label if the input field is of a hidden type. 
In Ory Kratos one-time code flow we have access to the input fields after the initial submit (step 2 of 3). Kratos will send back the nodes as hidden fields which will still have their labels attached.  
Related to this PR https://github.com/ory/kratos/pull/3516
Also fixes the resend button. The `auth-code-section` component did not render the hidden input field to specify the method when submitting the `resend` button. This is now fixed and the test assertions fixed.
> feat: hide label on hidden input type

- src/react-components/ory/sections/auth-code-section.tsx
- src/react-components/ory/user-auth-card.spec.tsx
- src/test/fixtures/registration.ts
- src/test/models/AuthPage.ts
Fixes duplicate hidden fields on the one-time code flow. 
Related to changes in https://github.com/ory/kratos/pull/3516
> fix: duplicate hidden input fields on `auth-code-section`

- src/react-components/ory/helpers/node.spec.tsx
- src/react-components/ory/helpers/node.tsx
Fixes Recovery, Verification and one-time code resend button. Adds the `formnovalidate` property based on the label id.
I've added tests for this now to catch such regressions in the future. 
Since this is a UI only implementation it was hard to catch. 
> fix: button with formnovalidate

- package-lock.json
- package.json
- src/react-components/ory/user-auth-card.spec.tsx
- src/react-components/ory/user-auth-card.tsx
- src/test/fixtures/login.ts
Fixes the two-factor confirmation card. Also adds the identifier to the card as we do with a normal login refresh flow.
> fix: two factor confirmation card

- examples/react-spa/README.md
- examples/react-spa/src/Login.tsx
- examples/react-spa/src/Recovery.tsx
- examples/react-spa/src/Registration.tsx
- examples/react-spa/src/Verification.tsx
- src/react-components/button-link.tsx
Use the `login_challenge` query parameter in the react-spa example when provided. 
Update the `CustomHref` type to be usable. 
> fix: `CustomHref` and update react-spa example

- examples/nextjs-spa/src/pages/recovery.tsx
- examples/nextjs-spa/src/pages/verification.tsx
- examples/preact-spa/src/recovery.tsx
- examples/preact-spa/src/verification.tsx
- examples/react-spa/src/Recovery.tsx
- examples/react-spa/src/Verification.tsx
- src/react-components/ory/helpers/filter-flow-nodes.tsx
> fix: use unique keys for flow nodes

- README.md
- examples/nextjs-spa/src/components/layout.tsx
- examples/nextjs-spa/src/pages/registration.tsx
- examples/preact-spa/src/login.tsx
- examples/preact-spa/src/main.tsx
- examples/preact-spa/src/recovery.tsx
- examples/preact-spa/src/register.tsx
- examples/preact-spa/src/verification.tsx
- examples/react-spa/src/Login.tsx
- examples/react-spa/src/Recovery.tsx
- examples/react-spa/src/Registration.tsx
- examples/react-spa/src/main.tsx
- src/react-components/provider.tsx
Adds custom language support to the `IntlProvider`. This allows users of `ory/elements` to specify and provide their own custom translations without needing to add it to the `ory/elements` repository.
> feat: allow custom languages in `IntlProvider`

- packages/markup/vite.config.ts
- packages/preact/vite.config.ts
- packages/react/vite.config.ts
This PR simplifies class overrides by providing a prefix name for the generated CSS classes. 
In this case we add a prefix `ory_elements__` to each class name.
The format is as follows: ory_elements__<class name>_<variant|size>__hash
Example generated classes:
`ory_elements__button_social__i8n2ik0`
`ory_elements__button_social_size_medium__ecxsa2d`
`ory_elements__button_social_variant_semibold__xas31dg`
See this discussion for more details
https://github.com/ory/elements/discussions/162
> feat: prefix the css class names

- src/react-components/provider.tsx
This PR supresses the warnings from react-intl about pre-compiling the messages. See also https://github.com/formatjs/formatjs/pull/3506
> chore: suppress react-intl warnings

- examples/react-spa/src/Registration.tsx
- examples/react-spa/src/Verification.tsx
Add support inside the examples to continue with the verification flow if applicable.
> feat: continue with the verification flow after registration

- examples/nextjs-spa/src/pages/settings.tsx
- examples/preact-spa/src/settings.tsx
- examples/react-spa/src/Settings.tsx
- src/locales/de.json
- src/locales/en.json
- src/locales/es.json
- src/locales/fr.json
- src/locales/nl.json
- src/locales/pl.json
- src/locales/pt.json
- src/locales/se.json
- src/markup-components/components.ts
- src/react-components/ory/user-settings-card.tsx
- src/react-components/ory/user-settings-screen.tsx
- src/stories/Ory/AuthSettings.stories.tsx
- src/stories/Ory/SettingsScreen.stories.tsx
> feat: add back button to settings screen

- src/assets/passwordInput.js
- src/react-components/ory/user-logout-card.tsx
Reverts ory/elements#171
This didn't actually work. The reason is, that the click event fires before the submit event of the enclosing form, and disabling the button in the event stops event propagation.
There are a few [solutions](https://stackoverflow.com/a/5691065), but IMO we should just get this right in AX2 before spending any more time on this. The underlying issue is fixed either way, and this was purely cosmetic. (From https://github.com/ory/elements/pull/171#issuecomment-1866225524)
> revert: disable button on submit

- packages/elements-react/src/tests/jest/test-utils.tsx
- packages/elements-react/src/theme/default/components/card/header.tsx
- packages/elements-react/src/theme/default/utils/__tests__/__snapshots__/constructCardHeader.spec.ts.snap
- packages/elements-react/src/theme/default/utils/__tests__/constructCardHeader.spec.ts
- packages/elements-react/src/theme/default/utils/constructCardHeader.ts
- packages/elements-react/tsconfig.json
> fix: show identifier_first node in card header

- packages/elements-react/src/components/card/__tests__/card-two-step.spec.ts
- packages/elements-react/src/components/card/card-two-step.utils.ts
> fix: use correct node to detect two step registration

- package-lock.json
- packages/elements-react/api-report/elements-react-theme.api.json
- packages/elements-react/api-report/elements-react-theme.api.md
- packages/elements-react/package.json
- packages/elements-react/src/tests/jest/test-utils.tsx
- packages/elements-react/src/theme/default/components/default-component.spec.tsx
- packages/elements-react/src/theme/default/components/default-components.tsx
- packages/elements-react/src/theme/default/flows/login.tsx
- packages/elements-react/src/theme/default/flows/recovery.tsx
- packages/elements-react/src/theme/default/flows/registration.tsx
- packages/elements-react/src/theme/default/flows/settings.tsx
- packages/elements-react/src/theme/default/flows/verification.tsx
> fix: implement component merging instead of usign lodash

- packages/elements-react/src/theme/default/components/form/label.tsx
> fix: missing resend button on login & registration

- packages/elements-react/src/components/form/form.tsx
- packages/elements-react/src/context/form-state.test.ts
- packages/elements-react/src/context/form-state.ts
> fix: password validation error form state

- packages/elements-react/src/theme/default/components/card/current-identifier-button.tsx
> fix: current identifier button overflowing on long values

- .github/conventional_commits.json
- packages/elements-react/src/components/form/__snapshots__/form-resolver.test.tsx.snap
- packages/elements-react/src/components/form/form-provider.tsx
- packages/elements-react/src/components/form/form-resolver.test.tsx
- packages/elements-react/src/components/form/form-resolver.ts
- packages/elements-react/src/components/form/nodes/input.tsx
- packages/elements-react/src/theme/default/components/form/label.tsx
> feat(core): add react-hook form resolver

- packages/elements-react/jest.config.ts
- packages/elements-react/src/util/onSubmitRecovery.ts
> fix: handle recovery brute force protection

- examples/nextjs-spa/.eslintrc.json
> chore: add missing eslint to example

- packages/elements-react/src/components/settings/settings-card.tsx
- packages/elements-react/src/components/settings/webauthn-settings.tsx
> fix: passkey and webauthn in settings flow

- examples/nextjs-app-router/app/auth/login/page.tsx
- examples/nextjs-app-router/app/auth/recovery/page.tsx
- examples/nextjs-app-router/app/auth/registration/page.tsx
- examples/nextjs-app-router/app/auth/verification/page.tsx
- examples/nextjs-app-router/app/settings/page.tsx
- packages/elements-react/src/theme/default/components/card/current-identifier-button.tsx
- packages/nextjs/src/app/client.ts
- packages/nextjs/src/app/flow.test.ts
- packages/nextjs/src/app/flow.ts
- packages/nextjs/src/app/index.ts
- packages/nextjs/src/app/login.ts
- packages/nextjs/src/app/logout.ts
- packages/nextjs/src/app/recovery.ts
- packages/nextjs/src/app/registration.ts
- packages/nextjs/src/app/session.ts
- packages/nextjs/src/app/settings.ts
- packages/nextjs/src/app/utils.ts
- packages/nextjs/src/app/verification.ts
- packages/nextjs/src/utils/config.ts
The `getFlowFactory` allows developers of the `@ory/nextjs` package to define their own get login, registration, verification, recovery, and settings fetch logic, while keeping all of the error handling and state transition logic intact.
Most people should use `getLoginFlow` and other variants instead.
> feat: expose get flow factory

- packages/elements-react/src/theme/default/components/form/button.tsx
- packages/elements-react/src/theme/default/components/form/social.tsx
- packages/elements-react/tailwind.config.ts
https://github.com/user-attachments/assets/ad6a9215-dbe1-4bae-87a9-7ba0e853740f
Closes https://github.com/ory/elements/issues/329
> fix: only show loading indicator on clicked button

- packages/elements-react/.npmignore
- packages/elements-react/DEVELOPMENT.md
- packages/elements-react/LICENSE
- packages/elements-react/README.md
- scripts/release.sh
> chore: update README.md & development instructions

- packages/elements-react/src/components/card/card-two-step.tsx
- packages/elements-react/src/components/form/messages.tsx
> fix: validation message regression

- packages/elements-react/src/theme/default/components/form/captcha.tsx
> fix: use correct import paths

- packages/elements-react/src/theme/default/flows/error.tsx
> fix: correctly render test id for error card

- package-lock.json
- packages/elements-react/.stub-responses/login/1fa/saml/credential-select-password.json
- packages/elements-react/.stub-responses/login/1fa/saml/credential-select.json
- packages/elements-react/.stub-responses/login/1fa/saml/initial-form.json
- packages/elements-react/.stub-responses/registration/one-step/saml/initial-form.json
- packages/elements-react/.stub-responses/registration/two-step/saml/initial-form.json
- packages/elements-react/.stub-responses/settings/saml/with-provider.json
- packages/elements-react/package.json
- packages/elements-react/src/components/form/social.tsx
- packages/elements-react/stories/components/login/1fa/saml.stories.tsx
- packages/elements-react/stories/components/registration/one-step/saml.stories.ts
- packages/elements-react/stories/components/registration/two-step/saml.stories.ts
This PR implements support for Ory's native SAML integration by adding new Storybook stories and updating the filtering logic in the social buttons form.
- Added new Storybook stories for two-step registration, one-step registration, and first factor login using SAML.
- Updated the filtering logic in the social form component to include SAML nodes alongside OIDC nodes.
> feat: support SAML-native

- examples/nextjs-app-router/.env
- examples/nextjs-app-router/README.md
- examples/nextjs-pages-router/.env
- examples/nextjs-pages-router/README.md
- examples/nextjs-pages-router/pages/auth/login.tsx
- examples/nextjs-pages-router/pages/auth/recovery.tsx
- examples/nextjs-pages-router/pages/auth/registration.tsx
- examples/nextjs-pages-router/pages/auth/verification.tsx
- examples/nextjs-pages-router/pages/index.tsx
- packages/nextjs/README.md
- packages/nextjs/src/utils/rewrite.ts
- packages/nextjs/src/utils/sdk.test.ts
- packages/nextjs/src/utils/sdk.ts
Vercel publishes env vars sometimes prefixed, sometimes not with NEXT_PUBLIC_.
This patch tries to use both variants. Also, if a `vercel.app` domain is found, the middleware will do it's thing. Otherwise, it will use the custom domain.
Closes #482
> fix: correctly guess vercel environment

- README.md
- packages/nextjs/README.md
Needs https://github.com/ory/docs/pull/1730 to be merged
> docs: clarify use cases and document nextjs
