ory/elements

- src/react-components/codebox.tsx
- src/theme/codebox.css.ts
> fix: minor css issues

- src/react-components/ory/helpers/error-messages.tsx
- src/react-components/ory/helpers/node.tsx
- src/react-components/ory/user-auth-card.tsx
This PR fixes React key errors. Some components such as `UserAuthCard` rendering the 2FA nodes would throw react key errors.
> fix: react components throwing key erorrs

- src/react-components/ory/helpers/filter-flow-nodes.tsx
- src/react-components/ory/helpers/node.tsx
- src/react-components/ory/sections/lookup-secret-settings-section.tsx
- src/react-components/ory/sections/oidc-settings-section.tsx
- src/react-components/ory/sections/password-settings-section.tsx
- src/react-components/ory/sections/profile-settings-section.tsx
- src/react-components/ory/sections/totp-settings-section.tsx
- src/react-components/ory/sections/webauthn-settings-section.tsx
This fixes the button full width styling issues on the settings card by allowing the button props to be overridden.
> feat: expose inner node component props

- src/markup-components/index.ts
- src/react-components/ory/helpers/utils.ts
- src/react-components/ory/sections/oidc-section.tsx
- src/react-components/ory/sections/oidc-settings-section.tsx
- src/react-components/ory/user-error-card.tsx
- src/react-components/ory/user-settings-card.tsx
- src/stories/Ory/AuthError.stories.tsx
> fix: use lower-case abbreviations

- src/react-components/checkbox.tsx
- src/react-components/ory/helpers/node.tsx
- src/stories/Checkbox.stories.tsx
- src/stories/InputField.stories.tsx
- src/theme/checkbox.css.ts
> fix: checkbox helper text and label

- .github/workflows/release.yml
- CHANGELOG.md
- packages/markup/CHANGELOG.md
- packages/preact/CHANGELOG.md
- packages/react/CHANGELOG.md
- packages/test/CHANGELOG.md
> ci: add release step

- src/theme/card-gradient.css.ts
> fix: safari gradient card hover

- .github/workflows/playwright.yml
- .github/workflows/release.yml
> fix: use node 16 instead of 14

- .github/workflows/release.yml
> fix: use correct command

- src/theme/card-gradient.css.ts
- src/theme/menu-link.css.ts
Small fix to remove some obsolete css and fix the card-gradient z-index
> fix: z index on card-gradient

- README.md
Reorder and structure the readme
> feat: update Readme

- src/theme/card.css.ts
> fix: card breakpoint increased

- lerna.json
- package-lock.json
- packages/markup/package.json
- packages/preact/package.json
- packages/react/package.json
- packages/test/package.json
> fix: bump package version

- lerna.json
- package-lock.json
- packages/markup/package.json
- packages/preact/package.json
- packages/react/package.json
- packages/test/package.json
- src/react-components/ory/user-consent-card.tsx
> fix: consent remember checkbox

- .github/workflows/release.yml
- CHANGELOG.md
- README.md
- packages/markup/CHANGELOG.md
- packages/preact/CHANGELOG.md
- packages/react/CHANGELOG.md
- packages/test/CHANGELOG.md
This PR adds a `make format` step to the changelog generation to not introduce changelog files that do not conform to our format presets (and thus fail the formatting checks).
It also updates the README with some quick Typo fixes and the new instructions for the release process, please take another look at, thanks!
> fix: formatting issues

- src/react-components/button-link.tsx
- src/react-components/ory/helpers/node.tsx
- src/theme/button-link.css.ts
Fixes a few issues in the new anchor rendering, which I apparently was a bit too fast on merging. 
> fix: anchor rendering

- src/theme/colors.css.ts
> fix: missing color on color sprinkle

- src/markup-components/express.ts
- src/markup-components/express/index.d.ts
> fix: express support

- src/react-components/ory/helpers/error-messages.tsx
- src/stories/Ory/Auth.stories.tsx
- src/stories/Ory/verification-submit-flow.json
> fix: node success messages

- examples/react-spa/src/Dashboard.tsx
- examples/react-spa/src/Error.tsx
- examples/react-spa/src/Login.tsx
- examples/react-spa/src/Recovery.tsx
- examples/react-spa/src/Registration.tsx
- examples/react-spa/src/Settings.tsx
- examples/react-spa/src/Verification.tsx
- examples/react-spa/src/main.tsx
- examples/react-spa/src/sdk.ts
Implements error handling for examples react-spa API calls handling all returned error codes
Removed code 422 handling from verification where kratos does not send that
Eslint fixes
[53](https://github.com/ory/elements/issues/53)
> fix: error handling for react-spa 422 code

- examples/react-spa/src/Settings.tsx
> chore: add oidc to settings page

- examples/nextjs-spa/pages/settings.tsx
> fix: nextjs settings error messages

- src/react-components/ory/helpers/utils.ts
- src/react-components/ory/sections/identifier-info.tsx
- src/react-components/ory/sections/logged-info.tsx
- src/react-components/ory/user-auth-card.spec.tsx
- src/react-components/ory/user-auth-card.tsx
- src/stories/Ory/Auth.stories.tsx
- src/stories/Ory/login-flow-refresh.json
- src/test/Fixtures.ts
- src/theme/identifier.css.ts
Implements [#3288](https://github.com/ory-corp/cloud/issues/3288)
> feat: add info about used identifier

- src/theme/button-social.css.ts
- src/theme/consts.ts
- src/theme/theme.css.ts
- src/theme/typography.css.ts
> fix: can override fonts for regular and mono

- src/react-components/ory/helpers/node.tsx
Changes the `id` of the resend code button to use the correct ID.
https://github.com/ory/kratos/pull/3067 depends on this
> fix: update id of resend code button

- examples/nextjs-spa/src/pages/error.tsx
- examples/nextjs-spa/src/pages/index.tsx
- examples/nextjs-spa/src/pages/login.tsx
- examples/nextjs-spa/src/pages/logout.tsx
- examples/nextjs-spa/src/pages/recovery.tsx
- examples/nextjs-spa/src/pages/registration.tsx
- examples/nextjs-spa/src/pages/settings.tsx
- examples/nextjs-spa/src/pages/verification.tsx
- examples/nextjs-spa/src/pkg/helpers.ts
- examples/nextjs-spa/src/pkg/hooks.tsx
- examples/nextjs-spa/src/pkg/sdk.tsx
Implements error handling for example nextjs-spa API calls handling all returned error codes
Flow handling changed to follow the react-spa format
Fix issues with refreshing pages
[Issue 71](https://github.com/ory/elements/issues/71)
[Issue 79](https://github.com/ory/elements/issues/79)
[Issue 80](https://github.com/ory/elements/issues/80)
> fix: api calls error handling

- src/react-components/ory/helpers/node.tsx
Fixes https://github.com/ory-corp/cloud/issues/4193
> fix: wrong autocomplete in input fields

- src/react-components/card.tsx
- src/theme/card.css.ts
- src/theme/divider.css.ts
Fixes the `<hr>` and `<img>` tags when using a global css override to reset browser styling.
The `<hr>` tag will now have `margin: auto` on all sides, pushing it to be centered in the element and removing excess space top and bottom. This will cause a change in the Ory components which will reduce their overall height. It is a small change and shouldn't have much impact on the overall look. 
> fix: hr and img tags shouldn't break with global css overrides

- src/react-components/ory/user-auth-card.spec.tsx
- src/react-components/ory/user-auth-card.tsx
- src/stories/Ory/Auth.stories.tsx
See also: https://github.com/ory/elements/pull/108
> feat: add option to disable user signup on login flow page

- package-lock.json
- package.json
> chore: bump to @ory/client v1.1.39

- src/common/useIdWithFallback.ts
- src/react-components/checkbox.tsx
- src/react-components/codebox.tsx
- src/react-components/input-field.tsx
- src/react-components/nav.tsx
Originated in SEO improvements for the website, but should benefit everyone :) Having inputs and labels associated with each other improves accessibility, as screen readers know how to announce inputs better. It also improves things for sighted users, as the inputs become focusable / toggleable via a click on the label. Using unique IDs is good for avoiding ID collisions with users' websites and necessary for allowing multiple uses of the same component.
> feat: associate all inputs with labels via unique IDs

- src/common/useIdWithFallback.ts
This PR fixes a compile error in projects using `React 17`. The change introduced in #113 implements unique IDs for components assuming that the `useId` react hook will be available. The proposed fix changes the import format to exclude the `useId` import from the build.
Sample dependencies to reproduce the issue:
```json
"dependencies": {
"@ory/elements": "0.0.1-beta.7",
"loader-utils": "3.2.1",
"react": "17.0.2",
"react-dom": "17.0.2",
"react-scripts": "5.0.1"
},
"devDependencies": {
"@types/react": "17.0.2",
"@types/react-dom": "17.0.2",
"typescript": "5.0.2"
},
```
> fix: compile error useId only available in react18

- src/react-components/ory/sections/oidc-section.tsx
- src/react-components/ory/user-auth-card.tsx
When in an OIDC flow the traits of the prefilled data might be missing once redirected back from the OIDC provider.
1. Login with X
2. Redirect back to registration page
3. Show prefilled traits it could populate & missing traits (error)
4. Enter missing traits and click continue
Step 3 works since the traits are still mapped under a different group:
In some cases the UI would be shown with only a `continue` button if an error occurred on a non-oidc group. 
This would thus create an empty form with only the `continue` button.
> fix: oidc should show pre-filled traits and missing traits

- README.md
> feat: ory elements banner

- README.md
> style: format

- src/common/useIdWithFallback.ts
useId does not fallback now when the React import is null. This means express cannot use the `@ory/elements-markup`
package.
```shell
TypeError: Cannot read properties of null (reading 'useId')
at ln (/home/benehiko/Github/elements/packages/markup/dist/index.umd.js:29:1199)
at Nav$1 (/home/benehiko/Github/elements/packages/markup/dist/index.umd.js:69:17981)
at Nav (/home/benehiko/Github/elements/packages/markup/dist/index.umd.js:173:19625)
at navigationMenu (/home/benehiko/Github/kratos-selfservice-ui-node/src/pkg/ui.ts:83:13)
at /home/benehiko/Github/kratos-selfservice-ui-node/src/routes/welcome.ts:33:26
at step (/home/benehiko/Github/kratos-selfservice-ui-node/src/routes/welcome.ts:33:23)
at Object.next (/home/benehiko/Github/kratos-selfservice-ui-node/src/routes/welcome.ts:14:53)
at …
```
> fix: fallbacks for non-react client

- src/common/useIdWithFallback.ts
> fix: add missing return to `useIdWithFallback`

- src/theme/card.css.ts
> chore: fix error card width

- src/react-components/ory/helpers/error-messages.tsx
- src/react-components/ory/helpers/node.tsx
I guess we should add at least one other language to chromatic as well?
> fix: global error message translations

- examples/nextjs-spa/src/styles/Dashboard.module.css
- examples/nextjs-spa/src/styles/globals.css
- examples/preact-spa/index.html
- examples/preact-spa/package.json
- examples/preact-spa/src/app.tsx
- examples/react-spa/index.html
- examples/react-spa/package.json
- examples/react-spa/src/Dashboard.tsx
- package-lock.json
- package.json
- packages/markup/package.json
- packages/preact/package.json
- packages/react/package.json
- playwright/index.html
- src/assets/inter-font.css
Updates the following packages:
- Vite
- Storybook
- Ory Client
- Typescript
- Vanilla-extract
The examples have also been updated to use the latest Ory client.
Some npm audit vulnerabilities were found and fixed:
- Vite 4.0.4 -> 4.0.5 in Preact
- `tough-cookie` from `@ory/integrations` (unused but override the pacakge anyway)
> chore: update packages

- src/react-components/ory/helpers/node.tsx
> feat: properly style unlink button as well

- src/react-components/ory/helpers/user-auth-form.tsx
- src/react-components/ory/sections/passwordless-section.tsx
- src/react-components/ory/sections/profile-section.tsx
- src/react-components/ory/user-auth-card.tsx
- src/ui/index.ts
> fix: include hidden passkey fields in form

- .github/workflows/release.yml
> chore: support pre-releases in ci

- src/react-components/ory/helpers/utils.ts
Account Experience Registration Crash ory/network#389
ory/network#389 
> fix: react-components hasHiddenIdentifier, null.some error

- src/react-components/ory/sections/passwordless-section.tsx
> fix: remove extra webauthn nodes from passwordless section

- .github/workflows/release.yml
- package-lock.json
> fix: add missing nx version step

- .github/workflows/ci.yml
- package-lock.json
- src/react-components/ory/user-auth-card.tsx
> feat: show a specific cancel message on account linking form

- .github/.conventional_commits.json
> chore: add deps-dev to cc scopes

- package-lock.json
- package.json
> chore: update react-intl

- packages/elements-react/src/locales/sv.json
- packages/elements-react/src/theme/default/components/form/label.tsx
> fix: use translations in more missing places

- packages/elements-react/src/components/form/form.tsx
- packages/elements-react/src/components/form/section.tsx
- packages/elements-react/src/components/settings/oidc-settings.tsx
- packages/elements-react/src/components/settings/passkey-settings.tsx
- packages/elements-react/src/components/settings/recovery-codes-settings.tsx
- packages/elements-react/src/components/settings/settings-card.tsx
- packages/elements-react/src/components/settings/totp-settings.tsx
- packages/elements-react/src/components/settings/webauthn-settings.tsx
- packages/elements-react/src/theme/default/components/default-components.tsx
- packages/elements-react/src/theme/default/components/form/social.tsx
- packages/elements-react/src/util/ui/__test__/ui.spec.ts
- packages/elements-react/tsconfig.json
> chore: settings component override API

- packages/elements-react/src/components/form/nodes/input.tsx
- packages/elements-react/src/theme/default/components/form/pin-code-input.tsx
> fix: duplicate resend button on recovery & verification

- .github/workflows/chromatic.yml
- .github/workflows/ci.yml
- nx.json
> chore(ci): enable turbosnap

- packages/elements-react/src/components/form/form-helpers.ts
- packages/elements-react/src/theme/default/components/form/input.tsx
- packages/elements-react/src/theme/default/components/settings/settings-oidc.tsx
> fix: oidc linking & unlinking form properties

- packages/elements-react/src/components/form/messages.tsx
> fix: hide two step registration message

- packages/elements-react/src/util/onSubmitSettings.ts
> fix: redirect to login if session expired during settings

- packages/elements-react/src/components/form/form.tsx
> feat: force OIDC account selection on settings

- .github/workflows/pm.yml
> feat: add project board automation

- packages/elements-react/tailwind.config.ts
> fix: use --font-sans CSS variable for font

- packages/elements-react/src/theme/default/components/card/auth-methods.tsx
> feat: add test ids to components

- packages/elements-react/src/components/form/form-helpers.ts
- packages/elements-react/src/components/form/messages.tsx
- packages/elements-react/src/components/form/social.tsx
- packages/elements-react/src/context/form-state.test.ts
- packages/elements-react/src/context/form-state.ts
- packages/elements-react/src/locales/de.json
- packages/elements-react/src/locales/en.json
- packages/elements-react/src/locales/es.json
- packages/elements-react/src/locales/fr.json
- packages/elements-react/src/locales/nl.json
- packages/elements-react/src/locales/pl.json
- packages/elements-react/src/locales/pt.json
- packages/elements-react/src/locales/sv.json
- packages/elements-react/src/theme/default/components/card/header.tsx
- packages/elements-react/src/theme/default/utils/__tests__/__snapshots__/constructCardHeader.spec.tsx.snap
- packages/elements-react/src/theme/default/utils/__tests__/constructCardHeader.spec.tsx
- packages/elements-react/src/theme/default/utils/constructCardHeader.ts
> feat: enable proper account linking flows

- src/stories/Button.stories.tsx
- src/stories/ButtonSocial.stories.tsx
- src/stories/Card.stories.tsx
- src/stories/Checkbox.stories.tsx
- src/stories/Codebox.stories.tsx
- src/stories/Divider.stories.tsx
- src/stories/GradientCard.stories.tsx
- src/stories/InputField.stories.tsx
- src/stories/Message.stories.tsx
- src/stories/Nav.stories.tsx
- src/stories/Ory/Auth.stories.tsx
- src/stories/Ory/AuthError.stories.tsx
- src/stories/Ory/AuthSettings.stories.tsx
- src/stories/Ory/Consent.stories.tsx
- src/stories/Ory/Logout.stories.tsx
> chore: migrate legacy stories to new story format

- examples/nextjs-spa/.eslintrc.json
> revert: add missing eslint to example

- packages/nextjs/src/middleware/middleware.ts
> fix: use correct host value in middleware

- .github/workflows/ci.yml
- examples/nextjs-app-router/package.json
- examples/nextjs-pages-router/package.json
- nx.json
- package-lock.json
> chore: fix next js release version

- packages/elements-react/src/context/form-state.ts
> fix: don't short circuit code method selector

- src/react-components/button-social.tsx
> fix: brand logic

- .github/workflows/chromatic.yml
- package-lock.json
- package.json
> chore: don't pin chromatic ci

- packages/elements-react/src/locales/de.json
- packages/elements-react/src/locales/en.json
- packages/elements-react/src/locales/es.json
- packages/elements-react/src/locales/fr.json
- packages/elements-react/src/locales/nl.json
- packages/elements-react/src/locales/pl.json
- packages/elements-react/src/locales/pt.json
- packages/elements-react/src/locales/sv.json
- packages/elements-react/src/util/i18n/index.ts
- src/locales/pl.json
> fix: translate {property} in missing property validation message

- packages/elements-react/src/theme/default/components/card/auth-method-list-item.tsx
> fix: remove untranslated aria label from auth list item

- nx.json
- scripts/release.sh
> chore: support PR pre-releases

- packages/elements-react/src/theme/default/components/card/footer.tsx
Closes https://github.com/ory/network/issues/281
> fix: hide registration link again

- packages/elements-react/src/theme/default/components/card/footer.tsx
- packages/elements-react/stories/components/login/1fa/all.stories.ts
adds story for https://github.com/ory/elements/pull/387
> chore: add login registration disabled story

- examples/nextjs-app-router/package.json
- examples/nextjs-pages-router/package.json
- examples/nextjs-spa/package.json
- package-lock.json
> chore: add missing dependencies in examples

- scripts/release.sh
When using the release script it uses the nx cache in the build script. This for some reason removes the d.ts files for the tailwind theme data. The fix is to force a rebuild using the --skip-nx-cache flag.
> chore: force rebuild in release script

- package-lock.json
- packages/elements-react/package.json
> chore: broaden react peer dep version constraints

- .github/workflows/pm.yml
> chore: exempt renovate PRs from board sync

- packages/elements-react/src/components/card/card-two-step.tsx
- packages/elements-react/src/components/settings/settings-card.tsx
- packages/elements-react/src/locales/de.json
- packages/elements-react/src/locales/en.json
- packages/elements-react/src/theme/default/components/card/current-identifier-button.test.ts
- packages/elements-react/src/theme/default/components/card/current-identifier-button.tsx
- packages/elements-react/src/theme/default/components/card/footer.tsx
- packages/elements-react/src/theme/default/components/form/group-container.tsx
- packages/elements-react/src/util/childCounter.ts
- packages/elements-react/src/util/nodes.ts
- packages/elements-react/src/util/ui/__test__/ui.spec.ts
- packages/elements-react/src/util/ui/index.ts
> fix: two-step registration back button

- packages/elements-react/src/theme/default/components/form/consent-scope-checkbox.tsx
> fix: add missing test id to scope checkbox label

- packages/elements-react/src/theme/default/components/card/current-identifier-button.tsx
> fix: use correct testid

- packages/elements-react/.stub-responses/login/1fa/organization/initial-form.json
- packages/elements-react/.stub-responses/login/1fa/organization/selected-email.json
- packages/elements-react/.stub-responses/registration/two-step/organization/initial-form.json
- packages/elements-react/.stub-responses/registration/two-step/organization/organization-providers.json
- packages/elements-react/stories/components/login/1fa/organization.stories.ts
- packages/elements-react/stories/components/registration/two-step/organization.stories.ts
> chore: add organizations to storybook

- package-lock.json
- packages/elements-react/.stub-responses/login/1fa/all-methods/initial-form.json
- packages/elements-react/package.json
- packages/elements-react/src/components/card/card-two-step.tsx
- packages/elements-react/src/theme/default/components/form/button.tsx
- packages/elements-react/src/theme/default/components/form/social.tsx
- packages/elements-react/src/util/ui/__test__/.fixtures/initial-form.json
- packages/elements-react/src/util/ui/__test__/.fixtures/omit-hidden-input.json
- packages/elements-react/src/util/ui/__test__/ui.spec.ts
- packages/elements-react/src/util/ui/index.ts
Resolves a regression introduced in the `method_active` flow by fixing an issue in `useNodesGroups` which incorrectly omitted nodes from form rendering.
Resolves an `onclick` warning in DefaultButton.
> fix: missing hidden field regression

- packages/elements-react/.stub-responses/login/1fa/password/initial-form.json
- packages/elements-react/.stub-responses/login/1fa/password/missing-email.json
- packages/elements-react/.stub-responses/login/1fa/password/wrong-credentials.json
- packages/elements-react/.stub-responses/registration/two-step/all-methods/code-sent-error.json
- packages/elements-react/.stub-responses/registration/two-step/all-methods/code-sent.json
- packages/elements-react/.stub-responses/registration/two-step/all-methods/passkey-error.json
- packages/elements-react/.stub-responses/registration/two-step/all-methods/password-validation-error.json
- packages/elements-react/.stub-responses/registration/two-step/all-methods/webauthn-error.json
- packages/elements-react/src/components/card/card-two-step.tsx
- packages/elements-react/src/components/form/form.tsx
- packages/elements-react/stories/components/registration/two-step/all-methods.stories.ts
> chore: add more storybook stories

- packages/elements-react/src/theme/default/components/form/button.tsx
- packages/elements-react/src/theme/default/components/form/checkbox.tsx
- packages/elements-react/src/theme/default/components/form/image.tsx
- packages/elements-react/src/theme/default/components/form/input.tsx
- packages/elements-react/src/theme/default/components/form/link-button.tsx
- packages/elements-react/src/theme/default/components/form/social.tsx
- packages/elements-react/src/util/omitAttributes.ts
> fix: always omit conflicting keys

- packages/elements-react/stories/components/settings/all-2fa.stories.ts
- packages/elements-react/stories/components/settings/all.stories.tsx
- packages/elements-react/stories/components/settings/lookup_secrets.stories.ts
- packages/elements-react/stories/components/settings/oidc.stories.ts
- packages/elements-react/stories/components/settings/passkey.stories.ts
- packages/elements-react/stories/components/settings/settings.tsx
- packages/elements-react/stories/components/settings/totp.stories.ts
- packages/elements-react/stories/components/settings/webauthn.stories.ts
> fix: add missing settings padding

- packages/elements-react/src/components/card/card-two-step.tsx
> chore: remove console.log

- packages/elements-react/src/theme/default/components/card/footer.tsx
Fixes https://github.com/ory/elements/issues/471
> fix: add missing color class to registration footer

- packages/elements-react/src/theme/default/components/form/input.tsx
- packages/elements-react/src/theme/default/components/settings/settings-totp.tsx
> fix: totp cleared on validation error

- packages/elements-react/src/components/card/card-two-step.tsx
- packages/elements-react/src/components/form/form.tsx
Recent fixes to the two-step auth card spacing introduced a regression where the "No authentication methods are available for this request. Please contact the site or app owner." messages was missing.
> fix: re-add missing error message when no methods provided

- packages/elements-react/api-report/elements-react.api.json
- packages/elements-react/api-report/elements-react.api.md
- packages/elements-react/src/context/form-state.test.ts
- packages/elements-react/src/theme/default/components/card/header.tsx
- packages/elements-react/src/theme/default/utils/__tests__/__snapshots__/constructCardHeader.spec.tsx.snap
- packages/elements-react/src/theme/default/utils/constructCardHeader.ts
- packages/elements-react/src/util/test-id.ts
> fix: add test id to header messages

- packages/elements-react/src/theme/default/components/form/social.tsx
- packages/elements-react/src/theme/default/provider-logos/generic.svg
- packages/elements-react/src/theme/default/provider-logos/index.ts
> fix: adjust design of generic OIDC provider

- packages/elements-react/src/theme/default/components/form/social.tsx
- packages/elements-react/src/theme/default/components/settings/settings-oidc.tsx
> chore: use proper generic OIDC logo

- packages/elements-react/src/context/__snapshots__/component.test.tsx.snap
- packages/elements-react/src/context/component.test.tsx
- packages/elements-react/src/context/component.tsx
> fix: sort captcha before submit button

- packages/elements-react/src/theme/default/components/card/footer.tsx
- packages/elements-react/src/theme/default/components/form/checkbox.tsx
> fix: add missing testids to method selector and checkbox

- package-lock.json
- package.json
- packages/elements-react/.storybook/main.ts
- packages/elements-react/.storybook/preview.tsx
- packages/elements-react/stories/utils.ts
- packages/elements-react/tsconfig.json
> chore: stabilize stories

- packages/elements-react/src/context/form-state.ts
- packages/elements-react/src/theme/default/components/card/footer.test.tsx
- packages/elements-react/src/theme/default/components/card/footer.tsx
> fix: re-enable method chooser on mfa method active screens

- packages/elements-react/api-report/elements-react.api.json
- packages/elements-react/api-report/elements-react.api.md
- packages/elements-react/src/context/form-state.ts
- packages/elements-react/src/theme/default/components/card/footer.tsx
> chore: clarify form state reducer naming

- .github/workflows/chromatic.yml
- renovate.json
> chore: reduce renovate noise

- packages/elements-react/src/util/onSubmitLogin.ts
- packages/elements-react/src/util/onSubmitRecovery.ts
- packages/elements-react/src/util/onSubmitRegistration.ts
- packages/elements-react/src/util/onSubmitSettings.ts
- packages/elements-react/src/util/onSubmitVerification.ts
- packages/elements-react/src/util/sdk-helpers/__test__/continueWith.spec.ts
- packages/elements-react/src/util/sdk-helpers/__test__/error.spec.ts
- packages/elements-react/src/util/sdk-helpers/__test__/ui.spec.ts
- packages/elements-react/src/util/sdk-helpers/__test__/utils.spec.ts
- packages/elements-react/src/util/sdk-helpers/continueWith.ts
- packages/elements-react/src/util/sdk-helpers/error.ts
- packages/elements-react/src/util/sdk-helpers/flowTypes.ts
- packages/elements-react/src/util/sdk-helpers/index.ts
- packages/elements-react/src/util/sdk-helpers/ui.ts
- packages/elements-react/src/util/sdk-helpers/urlHelpers.ts
- packages/elements-react/src/util/sdk-helpers/utils.ts
- packages/elements-react/src/util/ui/__test__/ui.spec.ts
Resolves an issue where `handleFlowError` would not properly detect the error due to incorrect control flows.
> fix: incorrect if branching in handle error

- packages/elements-react/src/context/form-state.ts
> fix: properly detect OIDC account linking

- packages/elements-react/DEVELOPMENT.md
- scripts/release.sh
> chore: support rc in release script
